language: cpp
compiler:
  - gcc
  - clang
before_script:
  - ./configure --enable-version=18,19,20
script: rake
branches:
  only:
    - tmp/for_travis-ci
notifications:
  recipients:
    - kachick1@gmail.com
rvm:
  - 1.8.7
  - 1.9.3
